name: Authorize Org
description: 'Authorize an org using SF CLI and Cumulus with an SFDX Auth URL'
inputs:
  auth-url:
    description: 'SFDX auth URL'
    required: true
  org-name:
    description: 'Name of the org'
    required: true
  dev-hub:
    description: 'Set org as default Dev Hub'
    required: true
    default: false
runs:
    using: "composite"
    steps:
      - name: Authenticate to Org
        run: |
          echo '${{ inputs.auth-url }}' > auth_file
          if [ '${{ inputs.dev-hub }}' == 'true' ] || [ '${{ inputs.dev-hub }}' == 'True' ]; then
            DEV_HUB='--set-default-dev-hub'
          else
            DEV_HUB=''
          fi
          sf org login sfdx-url --sfdx-url-file auth_file --alias '${{ inputs.org-name }}' $DEV_HUB
          rm auth_file
          if [ '${{ inputs.dev-hub }}' != 'true' ] && [ '${{ inputs.dev-hub }}' != 'True' ]; then
            cci org import '${{ inputs.org-name }}' '${{ inputs.org-name }}'
          fi
        shell: bash
